# Generated by Django 4.2.18 on 2025-02-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('license_plate', models.CharField(max_length=40)),
                ('availability_status', models.BooleanField(default=True)),
            ],
        ),
    ]
